import type { CategoriaId, Produto } from "./types"

export const CATEGORIAS: { id: CategoriaId; label: string }[] = [
  { id: "burgueres", label: "Burgueres" },
  { id: "super-burgueres", label: "Super Burgueres" },
  { id: "pastel", label: "Pastel" },
  { id: "porcoes", label: "Porcoes" },
  { id: "combos", label: "Combos e Barcas" },
  { id: "espetos", label: "Espetos" },
  { id: "jantinha", label: "Jantinha" },
  { id: "bebidas", label: "Bebidas" },
]

const burgerImg = (label: string) =>
  `/placeholder.svg?height=400&width=400&query=${encodeURIComponent(
    `dark moody photograph of a ${label} gourmet burger on dark background, top label text reading ${label.toUpperCase()}, cinematic lighting`,
  )}`

export const PRODUTOS: Produto[] = [
  // BURGUERES
  {
    id: "b-classico",
    nome: "Capitao Classico",
    nomeExibicao: "CAPITÃO CLÁSSICO",
    descricao: "O tradicional que conquistou os mares",
    preco: 25,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Classico"),
  },
  {
    id: "b-bacon",
    nome: "Capitao Bacon",
    nomeExibicao: "CAPITÃO BACON",
    descricao: "Para os amantes de bacon",
    preco: 28,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Bacon"),
  },
  {
    id: "b-cheddar",
    nome: "Capitao Cheddar",
    nomeExibicao: "CAPITÃO CHEDDAR",
    descricao: "Explosao de cheddar cremoso",
    preco: 28,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Cheddar"),
  },
  {
    id: "b-salada",
    nome: "Capitao Salada",
    nomeExibicao: "CAPITÃO SALADA",
    descricao: "Fresquinho e saboroso",
    preco: 28,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Salada"),
  },
  {
    id: "b-onion",
    nome: "Capitao Onion",
    nomeExibicao: "CAPITÃO ONION",
    descricao: "Com onions crocantes",
    preco: 30,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Onion"),
  },
  {
    id: "b-gorgonzola",
    nome: "Capitao Gorgonzola",
    nomeExibicao: "CAPITÃO GORGONZOLA",
    descricao: "Sabor sofisticado",
    preco: 30,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Gorgonzola"),
  },
  {
    id: "b-harry",
    nome: "Capitao Harry",
    nomeExibicao: "CAPITÃO HARRY",
    descricao: "Magico e delicioso",
    preco: 30,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Harry"),
  },
  {
    id: "b-cheese",
    nome: "Capitao Cheese",
    nomeExibicao: "CAPITÃO CHEESE",
    descricao: "Queijo por todos os lados",
    preco: 30,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Cheese"),
  },
  {
    id: "b-pig",
    nome: "Capitao Pig",
    nomeExibicao: "CAPITÃO PIG",
    descricao: "Carne suina suculenta",
    preco: 32,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Pig"),
  },
  {
    id: "b-vegetariano",
    nome: "Capitao Vegetariano",
    nomeExibicao: "CAPITÃO VEGETARIANO",
    descricao: "Sem carne, com sabor",
    preco: 28,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Vegetariano"),
  },
  {
    id: "b-kids",
    nome: "Capitao Kids",
    nomeExibicao: "CAPITÃO KIDS",
    descricao: "Para os pequenos piratas",
    preco: 22,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Kids"),
  },
  {
    id: "b-rucula",
    nome: "Capitao Rucula",
    nomeExibicao: "CAPITÃO RÚCULA",
    descricao: "Rucula fresca e parmesao",
    preco: 32,
    categoria: "burgueres",
    imagem: burgerImg("Capitao Rucula"),
  },

  // SUPER BURGUERES
  {
    id: "sb-tesouro",
    nome: "Super Tesouro",
    nomeExibicao: "SUPER TESOURO",
    descricao: "Burguer duplo com bacon e cheddar",
    preco: 42,
    categoria: "super-burgueres",
    imagem: burgerImg("Super Tesouro"),
  },
  {
    id: "sb-kraken",
    nome: "Super Kraken",
    nomeExibicao: "SUPER KRAKEN",
    descricao: "Triplo de carne, monstro do mar",
    preco: 52,
    categoria: "super-burgueres",
    imagem: burgerImg("Super Kraken"),
  },
  {
    id: "sb-galeao",
    nome: "Super Galeao",
    nomeExibicao: "SUPER GALEÃO",
    descricao: "Duplo costela com onion rings",
    preco: 48,
    categoria: "super-burgueres",
    imagem: burgerImg("Super Galeao"),
  },
  {
    id: "sb-corsario",
    nome: "Super Corsario",
    nomeExibicao: "SUPER CORSÁRIO",
    descricao: "Duplo picanha com cheddar",
    preco: 50,
    categoria: "super-burgueres",
    imagem: burgerImg("Super Corsario"),
  },

  // PASTEL
  {
    id: "p-carne",
    nome: "Pastel de Carne",
    nomeExibicao: "PASTEL DE CARNE",
    descricao: "Crocante e recheado",
    preco: 12,
    categoria: "pastel",
    imagem: burgerImg("Pastel de Carne"),
  },
  {
    id: "p-queijo",
    nome: "Pastel de Queijo",
    nomeExibicao: "PASTEL DE QUEIJO",
    descricao: "Queijo derretido na medida",
    preco: 12,
    categoria: "pastel",
    imagem: burgerImg("Pastel de Queijo"),
  },
  {
    id: "p-pizza",
    nome: "Pastel de Pizza",
    nomeExibicao: "PASTEL DE PIZZA",
    descricao: "Tomate, queijo e oregano",
    preco: 14,
    categoria: "pastel",
    imagem: burgerImg("Pastel de Pizza"),
  },
  {
    id: "p-frango",
    nome: "Pastel de Frango",
    nomeExibicao: "PASTEL DE FRANGO",
    descricao: "Frango com catupiry",
    preco: 14,
    categoria: "pastel",
    imagem: burgerImg("Pastel de Frango"),
  },

  // PORCOES
  {
    id: "po-fritas",
    nome: "Batata Frita",
    nomeExibicao: "BATATA FRITA",
    descricao: "Sequinha e crocante",
    preco: 22,
    categoria: "porcoes",
    imagem: burgerImg("Batata Frita"),
  },
  {
    id: "po-fritas-cheddar",
    nome: "Fritas com Cheddar e Bacon",
    nomeExibicao: "FRITAS CHEDDAR BACON",
    descricao: "Cheddar cremoso e bacon crocante",
    preco: 32,
    categoria: "porcoes",
    imagem: burgerImg("Fritas Cheddar Bacon"),
  },
  {
    id: "po-onion-rings",
    nome: "Onion Rings",
    nomeExibicao: "ONION RINGS",
    descricao: "Aneis de cebola crocantes",
    preco: 24,
    categoria: "porcoes",
    imagem: burgerImg("Onion Rings"),
  },
  {
    id: "po-frango-passarinho",
    nome: "Frango a Passarinho",
    nomeExibicao: "FRANGO A PASSARINHO",
    descricao: "Temperado e dourado",
    preco: 35,
    categoria: "porcoes",
    imagem: burgerImg("Frango a Passarinho"),
  },

  // COMBOS E BARCAS
  {
    id: "c-barca-pirata",
    nome: "Barca Pirata",
    nomeExibicao: "BARCA PIRATA",
    descricao: "2 burgueres, fritas e 2 refris",
    preco: 75,
    categoria: "combos",
    imagem: burgerImg("Barca Pirata"),
  },
  {
    id: "c-tripulacao",
    nome: "Combo Tripulacao",
    nomeExibicao: "COMBO TRIPULAÇÃO",
    descricao: "4 burgueres, 2 fritas, 4 refris",
    preco: 140,
    categoria: "combos",
    imagem: burgerImg("Combo Tripulacao"),
  },
  {
    id: "c-capitao",
    nome: "Combo Capitao",
    nomeExibicao: "COMBO CAPITÃO",
    descricao: "Burguer especial, fritas e refri",
    preco: 45,
    categoria: "combos",
    imagem: burgerImg("Combo Capitao"),
  },

  // ESPETOS
  {
    id: "e-carne",
    nome: "Espeto de Carne",
    nomeExibicao: "ESPETO DE CARNE",
    descricao: "Carne nobre na brasa",
    preco: 15,
    categoria: "espetos",
    imagem: burgerImg("Espeto de Carne"),
  },
  {
    id: "e-frango",
    nome: "Espeto de Frango",
    nomeExibicao: "ESPETO DE FRANGO",
    descricao: "Frango temperado na brasa",
    preco: 13,
    categoria: "espetos",
    imagem: burgerImg("Espeto de Frango"),
  },
  {
    id: "e-queijo",
    nome: "Espeto de Queijo",
    nomeExibicao: "ESPETO DE QUEIJO",
    descricao: "Queijo coalho dourado",
    preco: 14,
    categoria: "espetos",
    imagem: burgerImg("Espeto de Queijo"),
  },

  // JANTINHA
  {
    id: "j-fileto",
    nome: "Jantinha Fileto",
    nomeExibicao: "JANTINHA FILÉ",
    descricao: "File com fritas e arroz",
    preco: 38,
    categoria: "jantinha",
    imagem: burgerImg("Jantinha File"),
  },
  {
    id: "j-frango",
    nome: "Jantinha Frango",
    nomeExibicao: "JANTINHA FRANGO",
    descricao: "Frango grelhado, fritas e arroz",
    preco: 32,
    categoria: "jantinha",
    imagem: burgerImg("Jantinha Frango"),
  },

  // BEBIDAS
  {
    id: "be-coca-2l",
    nome: "Coca-Cola 2L",
    nomeExibicao: "COCA-COLA 2L",
    descricao: "Gelada para a tripulacao",
    preco: 14,
    categoria: "bebidas",
    imagem: burgerImg("Coca Cola 2L"),
  },
  {
    id: "be-coca-lata",
    nome: "Coca-Cola Lata",
    nomeExibicao: "COCA-COLA LATA",
    descricao: "350ml gelada",
    preco: 6,
    categoria: "bebidas",
    imagem: burgerImg("Coca Cola Lata"),
  },
  {
    id: "be-guarana",
    nome: "Guarana Antarctica",
    nomeExibicao: "GUARANÁ",
    descricao: "Lata 350ml",
    preco: 6,
    categoria: "bebidas",
    imagem: burgerImg("Guarana"),
  },
  {
    id: "be-suco",
    nome: "Suco Natural",
    nomeExibicao: "SUCO NATURAL",
    descricao: "Laranja, abacaxi ou maracuja",
    preco: 10,
    categoria: "bebidas",
    imagem: burgerImg("Suco Natural"),
  },
  {
    id: "be-agua",
    nome: "Agua Mineral",
    nomeExibicao: "ÁGUA MINERAL",
    descricao: "Com ou sem gas",
    preco: 4,
    categoria: "bebidas",
    imagem: burgerImg("Agua Mineral"),
  },
  {
    id: "be-cerveja",
    nome: "Cerveja Long Neck",
    nomeExibicao: "CERVEJA LONG NECK",
    descricao: "Heineken ou Stella",
    preco: 12,
    categoria: "bebidas",
    imagem: burgerImg("Cerveja Long Neck"),
  },
]

export function getProdutoPorId(id: string): Produto | undefined {
  return PRODUTOS.find((p) => p.id === id)
}
